version: "2"

services:
    app:
        image: dockerphp/nginx:7.2-stretch
        volumes:
            - .:/app
            - ./docker/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "8000:443"

#    blackfire:
#        image: blackfire/blackfire
#        environment:
#            BLACKFIRE_LOG_LEVEL: 4
#            BLACKFIRE_SERVER_ID:
#            BLACKFIRE_SERVER_TOKEN:
